from enum import Enum

class ServiceId(Enum):
    ACCOUNT = "account"
    AVATARS = "avatars"
    DATABASES = "databases"
    TABLESDB = "tablesdb"
    LOCALE = "locale"
    HEALTH = "health"
    PROJECT = "project"
    STORAGE = "storage"
    TEAMS = "teams"
    USERS = "users"
    VCS = "vcs"
    SITES = "sites"
    FUNCTIONS = "functions"
    PROXY = "proxy"
    GRAPHQL = "graphql"
    MIGRATIONS = "migrations"
    MESSAGING = "messaging"
